### ISSUE TITLE
User registration form

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#1]
Users are able to register to toolset using Facebook or Google accounts and via e-mail address. 

Registration form fields are:
- Name
- E-mail address
- Password

![screen shot 2016-09-19 at 14 10 19](https://cloud.githubusercontent.com/assets/380007/18630102/ec95f126-7e72-11e6-9b4e-ae89ec486610.png)

![screen shot 2016-08-17 at 12 04 11](https://cloud.githubusercontent.com/assets/380007/17730715/bbd90902-6472-11e6-8411-f498f2290c44.png)

**Comment by pjotrsavitski** [comment]
Registration form was added by this one 8d356a5586319f6ee240cecb985a1ebdf5a819b8, although it is not as fancy and lacks social logins along with translations.

**Comment by pjotrsavitski** [comment]
All done, the UI issues would be tackled later.
