### ISSUE TITLE
Playing a game - upload photo

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#10]
If task requires, user is able to upload a photo as a part of the answer or input. Uploaded image will be resized to 300px x 300px. Original image will be deleted from server.

**Comment by kaimikael** [comment]
This requires elaboration.  How will this photo be evaluated?  We don't really have the image-analysis skills in the project.  I propose this feature be dropped.

**Comment by pjotrsavitski** [comment]
This indeed seems to be something that is best done by humans. It could prove to be useful in some competition, that will have results manually evaluated anyway.

I suppose that there is software to analyse image content, but it could require additional resources on server side (this might not fit the Minimum Viable Product paradigm).

**Comment by pjotrsavitski** [comment]
Uploading has been implemented, it also involves preview of the image. The dimensions changed to 800x800 (up to).
