### ISSUE TITLE
Better Game finish and game results

### ISSUE THREAD

**Issue by pjotrsavitski** [SmartZoos/Toolset#101]
There is a need to change the Game Results dialog so that the user would understand what is going on. It might not be apparent to the user that the current dialog shown is not one for question, but is showing the results of the game and the game has already finished.

One solution could be to just display the text "Finished Activity Results" as the dialog header and/or some explanation text that would clearly state that it can not longer be played once all the questions have been answered and the Game has been marked as finished.

Another solution would be to use some colours/images/icons.

**Comment by pjotrsavitski** [comment]
For additional information please see #97 
It has the original issue and discussion.

**Comment by kaimikael** [comment]
There should be an indicator already in the activity list that this particular activity has already been played, like a highlighted marker "Done".
I think something like "These are your results" sounds friendlier and more informal than "finished activity results" :-)

**Comment by pjotrsavitski** [comment]
We could display a different button for the activity in the Listing and Full Views. It could be something like the dashboard shows. We could even show the resume button, in case this activity has been started but not completed yet.

Will think how could that be done in the most resource-friendly manner.

**Comment by kaimikael** [comment]
Nonono, in the most _player-friendly_ manner.  Resources have to adapt to user needs.

**Comment by pjotrsavitski** [comment]
@kaimikael Agree. I only meant that I would think of a solution that would also work fast and would not consume too much resources. Example: making a standalone Database query (or two) for each Activity displayed in the listing.

No player-unfriendliness intended.

**Comment by kaimikael** [comment]
We discussed earlier having “Read more about…” information for the questions.  This seems like an excellent place to put that button: The player can review their results, and for each question they also get a link to more information.
It will then be up to each zoo to maintain an info page (which potentially can simply be a list of links to further information) for each subject.  Note that multiple questions may share an info page, as we may have several different questions about, say, mountain goats, but they all point at a generic mountain goat info page.

**Comment by pjotrsavitski** [comment]
I remember the discussion, but was that so with any **Activity Item** within the system? Meaning that each time one creates/updates one the URL to any location could be added.

Will it be ok if those links are opened in new tabs/windows?

**Comment by pjotrsavitski** [comment]
@kaimikael Check attached screenshots, these show one possible visual solution to determine if user has played an activity or not. These have three states: **complete**, **ongoing** and **not played**. The difference between the first two is whether the user has finished the game or are there some unanswered question due to which the game could not be marked as complete.

We could easily put some texts or icons in there and have the same **play** button. I am not sure what would be the best solution (plain and simple text is hard to beat; especially with some icon which meaning might not be universally understandable).
![screen shot 2017-05-15 at 18 45 10](https://cloud.githubusercontent.com/assets/518331/26066301/0d3cf496-399f-11e7-8a38-1ba637d9222c.png)
![screen shot 2017-05-15 at 18 45 24](https://cloud.githubusercontent.com/assets/518331/26066312/0ef3f5fa-399f-11e7-8114-42a124d43a82.png)

**Comment by kaimikael** [comment]
I agree.  Text requires less explanation and is generally at least as easy to understand as icons.

**Comment by kaimikael** [comment]
And further to an earlier comment: yes, while I in general think we should cut down on the number of tabs in the game per se, Read More links would make sense to open in separate tabs, since you might want to save them for later reading.

**Comment by pjotrsavitski** [comment]
@kaimikael Opening no in new tab would be impossible, as that would prevent the gameplay on handheld devices. I've added a standalone issue for that one #109 I suppose it should be useful to keep each feature within its own issue.

**Comment by PatriciaMoller** [comment]
A suggestion for an end screen, consisting of Activity title and number of questions:
![screenshot endscreen](https://user-images.githubusercontent.com/26867575/30162710-297f7160-93d6-11e7-95fa-e8a61dbd6c34.png)
This puts the end of the game in focus. If the player wants they can review their answers.
![expanded](https://user-images.githubusercontent.com/26867575/30162745-50587dfe-93d6-11e7-9b77-826ba4fdc123.png)
I'd also suggest that the current Exit Game button leads back to the Activity list, rather than home page. It feels unnecessary to take them out of the game.

**Comment by PatriciaMoller** [comment]
Bumping this, as it is something Jens and I have been thinking about during some of recent tests.

We also noticed that some question types that are always "correct" did not show any result, just the question. Such as Match Pairs. That made the players feel a bit lost, when they didn't see the result of something they remember to have done in the game. Would it be possible to list the pairs? 

Would it be possible to show what the correct answer was, if you've answered incorrectly? Maybe have your submitted answer in bold, to differentiate?

Also pointing out red/green color blindness. Currently, if you answer correctly/incorrectly, the result shows a green or red radio button. I suggest using icon similar to the ones used in-game (Green check for correct, red X for incorrect) to maintain consistency.

**Comment by pjotrsavitski** [comment]
This issue has a lot of comments, ideas and requirements and has grown a bit unmanageable. Some of the outlined issues have already been solved (example: the URL the player is sent to when exiting the game).

I suppose that `Match Pairs` is the only question type (apart for the `Information`) that is missing the answer. We could show the pairs if that makes sense.

We do not have any correct textual answers, so I did not understand what to show as bold. The answer given by the players is already shown.

We are using an existing icon set, so we do not create new ones ourselves. I could suggest a few possibilities (size, logic and look are rather similar):
- `minus-circle-outline` for the incorrect single-choice
- `minus-box-outline` for the incorrect multiple-choice

I would also be happy to show the `<correct>/<total>` element.

**Comment by PatriciaMoller** [comment]
For the pairs, showing the pairs would probably be good, so the player can be reminded of what they have played. They'd probably have to be scaled down to not take up too much space while scrolling.

The text to have in bold was the answer you chose in correct/incorrect questions. Currently, in a One Correct Answer item, you only get to see if the answer you chose was correct/incorrect. You don't see which was right if you answered wrong. I thought if the player's choices are stylized/bolded, then they could be more easily distinguished.
![bolded result](https://user-images.githubusercontent.com/26867575/36849355-23c6c33c-1d64-11e8-814f-3de66b47e523.png)

Since the incorrect markers on the map use crosses/X-symbols, it'd probably be best if the results did as well.  close-box-outline and close-circle-outline might suit better. checkbox-marked-circle-outline and checkbox-marked-outline could work for correct answers
