### ISSUE TITLE
Explain lost GPS contact

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#102]
As a player I need to understand that GPS contact is lost.
If GPS contact is lost, the self marker disappears, but this is not explained within the game.  There should be an explanation that “Navigation is lost”.

**Comment by pjotrsavitski** [comment]
Have not had that once yet.

Should the game show some kind on screen with that or would it be sufficient to show an **alert** message?

**Comment by kaimikael** [comment]
We had quite a few GPS dropouts during our recent outing at Skansen, so it is a concern.
Ideally the warning should be graphics integrated on top of the game map that turns on when needed and disappears when signal returns – we don't want to break focus for the player.  @PatriciaMoller, suggestion for a nice design? 
I don't quite like the banner they use in Pokémon Go, but if we can't come up with anything better, something of that ilk.
`<img src="https://www.androidcentral.com/sites/androidcentral.com/files/styles/xlarge_wm_brw/public/article_images/2016/07/pokemon-go-android-gps-1.jpg">`

**Comment by pjotrsavitski** [comment]
I will get into that one quickly. I think that something like that would be good enough. Most of the apps I've used had something similar that caught the attention.

Lost GPS signal is a major issue in the gameplay. If proximity check is enabled (and that would mostly be so), then the questions could not be answered once the signal has been lost.

I will also try to investigate the **loss of player spot marker on GPS issues**. This should not be happening. The player marker could just freeze on the same spot, not disappear. That would be a big issue as certain features of the game **require** it to be present.

Made this one a high priority.
