### ISSUE TITLE
Allow clicking on entire activity to start playing

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#104]
As a player, I want to be able to just press on an activity in the list in order to start playing.
Currently, there is a smallish icon that a player has to press in order to start a game.  It would be easier and require less precision to just press the activity text in order to start playing.
I understand the icon is there since a logged-in user could either play, edit or delete an activity, but I am not sure the administration tasks should all be supported in the same list display as when one is looking for a game to play.

**Comment by pjotrsavitski** [comment]
In that case there is a need for a way to navigate to activity full view. If that is not needed, then we could change the logic.

That play/resume/results button could also be bigger than the other ones.  The edit and delete buttons are not available to normal users, unless that activity belongs to one.

**Comment by kaimikael** [comment]
I e, we need to be able to scroll the list of activities?  
I think it should work – a drag indicates scrolling and a press indicates activation.  Works fine in other mobile apps I'm using.

**Comment by pjotrsavitski** [comment]
@kaimikael The differentiation could be made. My concern was that user can go to the Full View page of Activity. If that is not needed, then we could remove the page as such.

Making the whole activity element within the listing support click-to-play logic is doable.

**Comment by pjotrsavitski** [comment]
I'm closing this one as we have just implemented the really huge button for playing.
