### ISSUE TITLE
Orient map according to compass

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#106]
As a player I would like the map display to align with the real world.
Not all devices have a compass, but at least in motion it is possible to detect the heading of a device. If this information is used to rotate the map display, it should become easier for a player to understand where to go for the next question.
Note that the rotation would have to be damped so as not to spin too fast for reading.

**Comment by pjotrsavitski** [comment]
Map orientation is plain impossible for the Google Maps JS API.

Showing the direction of movement is a different thing, but not the reorientation.

**Comment by pjotrsavitski** [comment]
Closing the issue as it is impossible to implement with JS API.
