### ISSUE TITLE
Reorganise game entry

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#107]
As a player, I want to start playing as soon as possible.
Currently the entry point to a game (http://toolset.smartzoos.eu/) is a page with information about the SmartZoos project, which is irrelevant to the typical player.  The player should instead immediately be allowed to choose a game to play.  Indeed, since we can figure out where the player is, we can immediately display the map view of the relevant zoo so as to contextualise the game.  The player can then be allowed to select a game from a list.
The number of tabs and menus should be minimised.

**Comment by pjotrsavitski** [comment]
What should the index page be like then? It would probably not be an index of all activities. Maybe a few that have been **promoted** by the Zoo people?

I would need some sketch and more information before we implement. Also are @tammets and @tirts OK with that change?

**Comment by tammets** [comment]
I think it's a question of activity listing page that could be served to user with predefined zoo. I'll sketch some possible solution.

**Comment by pjotrsavitski** [comment]
The index page has now got the **quickplay** button that would allow jumping to activities for a certain zoo. Is that enough and could this issue be marked as resolved? @kaimikael @tammets

**Comment by kaimikael** [comment]
I still think the index page should be gotten rid of completely – just show the play page immediately.  All the logos and explanations should be moved to an "About" page.
