### ISSUE TITLE
Warning/reminder when leaving Activity editing

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#111]
Currently, you can leave the page Activity creation/editing page without saving.
A warning pop-up,  "You have unsaved changes. Do you still want to leave?", would be appreciated to help not losing progress.

**Comment by pjotrsavitski** [comment]
That one should be doable. Should it be OK to always display that one, without any logic to check for changes to have actually taken place?

**Comment by PatriciaMoller** [comment]
Yes, I think it's okay for it to always pop-up. I don't think it matters much if there's a check or not. If the user have gone there to make changes, then they have to use the Save button to exit anyway.

Maybe have to say "You may have unsaved changes", instead of "You have[...]". A small thing, but since changes are not necessary to make the popup show, it feels like a more honest phrasing.
