### ISSUE TITLE
Correct/Incorrect marker should have different symbols

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#118]
While testing at Skansen 24/5, we were suggested to have different symbols for correct and incorrect in cases of red/green color blindness.
For example:
![icon preview](https://cloud.githubusercontent.com/assets/26867575/26500744/6b2e9e2e-4237-11e7-8812-9833985d3729.PNG) 

SVGs available here: [Cross](https://drive.google.com/open?id=0BwI6ykFZVgBJZzNXaTVVQXVEb2c), [Star](https://drive.google.com/open?id=0BwI6ykFZVgBJV3BNQnEzcmtOZU0), [Question](https://drive.google.com/open?id=0BwI6ykFZVgBJNmZNLVlTMHNPdFU), [Out of reach](https://drive.google.com/open?id=0BwI6ykFZVgBJXzNveUhWbzVQZzQ)

**Comment by pjotrsavitski** [comment]
I need a solid "green light" before making the change.

**Comment by kaimikael** [comment]
Well, I vote for.

**Comment by pjotrsavitski** [comment]
We would still need one more icon. The grey one for unreachable points. Not sure which symbol should that one have though.

**Comment by PatriciaMoller** [comment]
I think having the question mark one in gray, and making it overall darker, would be a safe option. 
![outof reach](https://cloud.githubusercontent.com/assets/26867575/26622781/be286d46-45eb-11e7-99b3-e49065818bcb.png)

**Comment by pjotrsavitski** [comment]
@PatriciaMoller Could you modify the original description to include the link to SVG for this darker one?

**Comment by PatriciaMoller** [comment]
Link as been added

**Comment by kaimikael** [comment]
There are unreachable points?

**Comment by pjotrsavitski** [comment]
These are the ones that could only be opened once nearby. Ny questions not close enough have these markers.

**Comment by kaimikael** [comment]
Ah, _unreached_ rather than unreachable :-)
