### ISSUE TITLE
Text-to-speech for questions?

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#119]
Text-to-speech for questions was suggested, in case the player can't or has difficulties reading.

Is it possible to use Google Text-to-Speech?

**Comment by pjotrsavitski** [comment]
Depends on API limitations and other details. But this is will surely be a lower priority than any of the features mentioned in the project proposal.

**Comment by pjotrsavitski** [comment]
I suppose we will not be doing that.

**Comment by PatriciaMoller** [comment]
This discussion mostly ran into the sand, but I don't think this, and other accessibility considerations, is something that should be completely disregarded in a final product. The clear benefits would be that visually impaired och people who has difficulty reading would be able to play. It could maybe even be useful during days where sunlight makes it hard to see the phone screen clearly. 

What would be the difficulties in implementing such a feature?

**Comment by pjotrsavitski** [comment]
There is a possibility to running into this feature having a cost. Using Cloud API's tends to have that.

It has also a lot of images and visuals that the game is not playable without.

**Comment by PatriciaMoller** [comment]
If it's data costs, then letting the player turn it on/off before play and being clear that the service might cost you extra would at least present the option. How demanding would it be? (Skansen is working on setting up WiFi for the park, so data should be a non-issue there)

I don't mean that the game has to be playable completely without visuals. In this case I'm mostly focusing on text. What about using alt-texts when possible, eg if images are used as answer options?

**Comment by pjotrsavitski** [comment]
It is not only the data transfer. It is a real cost for getting text into speech, if we are talking about using Google API.

Reading a lot of text (alto for images) would be confusing and overwhelming, in the end. Some question types could have user uploaded images or embedded videos.

We could have the alt texts, and we should have them even now, but that will not make it really playable and enjoyable experience.

The phones themselves should have the text to speech feature, but that is up to the user.
