### ISSUE TITLE
Last item in an activity cannot be answered

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#128]
I played through the entire ”En vandring på Skansen” yesterday.  When I got to the last question (Skånegården) nothing happened when I submitted the answer to the question.  I was able to close the popup box and the question icon indicated the question was still unanswered.  I made several attempts to answer, but none of the alternatives was accepted.

**Comment by pjotrsavitski** [comment]
I will try to give that a look. See if I could just play that activity and see what happens.

Should get there in a couple of days.

**Comment by pjotrsavitski** [comment]
This should be related to the issue fixed by a3b9b37b960b576e94fff9f6c3a21a00f7e6dcdc

The games were indeed finished, the issue was with the logging of activity, thus the AJAX call got an error core reply instead.
