### ISSUE TITLE
Add control over map layers

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#134]
I noticed the Skansen app allows the user to control the information visible on the map with a simple button, as shown in the attached video.  This looks like a simple but nice thing to add to our map, so that a player can choose to see the drawn map, the Google map, or the satellite view.
[maps.zip](https://github.com/SmartZoos/Toolset/files/1281041/maps.zip)

**Comment by pjotrsavitski** [comment]
We could also have something similar. The button that would just cycle through all the available map types.

We could even bring back the original MapTypeControls we have removed, if so desired. I would need the icons/images for the button to signal each state being changed (or to signal which one do we currently have).
