### ISSUE TITLE
Make Difficulty levels more concrete and easier to understand

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#136]
The current difficulty levels are very unclear for the user and activity creators.
As in #116, I propose an "Easy/Medium/Hard" scale.
The guideline for what each difficulty represents could be related to the amount of questions in the trail or the means of acquiring the answers (Example: Look at location -> Read signs-> External web searches)

**Comment by pjotrsavitski** [comment]
These should be implemented soon enough.

There are a few questions before I dig into that:
  - Would these values belong to the Activity itself and could be assigned/changes within the respective forms?
  - What would happen to the old values. Should we come up with some strategy to map these values to these newly added ones or should we just assign some default value instead and let the authors/admins change it to something meaningful? I do not have a good strategy on converting the range from 0 to 99 into (easy, medium, hard) right now.

**Comment by PatriciaMoller** [comment]
1. It would assigned through Activity creation. This is just another way to display the difficulty level, instead of having an 1-99 scale.

2. I think assigning them a default value (I suggest Medium) would be best. Would it be possible to send an mail alert about change, when it is out? I dare to say that most Activities don't currently have a representative difficulty or are meant to be final, so trying to convert them feels unneccesary. If notified, the ones who want to maintain their Activities know about it and change it them selves.

**Comment by pjotrsavitski** [comment]
Sending notifications would be possible. But it does not seem to be useful, as most of the content is there to just try out the system.

Going with medium is fine by me and should speed up the development cycle. I am almost sure I will be able to roll that change out next week.

**Comment by pjotrsavitski** [comment]
The change has been updated to the server. Search for Activities has also been changed.

**Comment by PatriciaMoller** [comment]
Looks great and feels much more approachable!

**Comment by pjotrsavitski** [comment]
Agree. I've used the default button classes for now as they were very close to what we needed. Some visual overhauls could be applied later, when all the functionality is there and working as it should.
