### ISSUE TITLE
Improved illustrations for badges

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#139]
@pjotrsavitski requested new icons/illustrations for the unlockable badges.

@pnella This may be something for us to sketch on at a later time?

Link: https://toolset.smartzoos.eu/badges

**Comment by Pnella** [comment]
Badges are finished, here's a link to the SVGs
https://drive.google.com/drive/folders/0B7ghDGIir49XSFRvY0s1NHRGWVE?usp=sharing

**Comment by pjotrsavitski** [comment]
It seems that lvl2 Gamer Badge image is incorrect. Seems to be the same as lvl4.

**Comment by Pnella** [comment]
Apologies, I've corrected the lvl2 Gamer Badge and the correct version should be in the shared folder.

**Comment by pjotrsavitski** [comment]
Thank you.

I will try to replace the existing ones as soon as possible.

**Comment by pjotrsavitski** [comment]
Should the PlayerBadgeV2 be used for the Social Login badge?

**Comment by Pnella** [comment]
Yes, that's what I had in mind.

**Comment by pjotrsavitski** [comment]
This is how it looks like now. The dimensions (so to say) for some images differ a bit, this makes some of the icons appear bigger than others, while still keeping the some size of the images shown. The shape itself proportionally taking more space within the image canvas.

Here are a few screenshots (showcasing the list of badges and the achieved ones from the profile page):
<img width="444" alt="screen shot 2017-09-21 at 11 52 56" src="https://user-images.githubusercontent.com/518331/30687452-f7391f3c-9ec3-11e7-9813-f7c6da4afb54.png">
<img width="665" alt="screen shot 2017-09-21 at 11 53 10" src="https://user-images.githubusercontent.com/518331/30687457-f95863e0-9ec3-11e7-9d60-af011be53434.png">
<img width="748" alt="screen shot 2017-09-21 at 11 53 49" src="https://user-images.githubusercontent.com/518331/30687460-fba26d6c-9ec3-11e7-8f4b-dea64d11733b.png">

We could still make some changes before it goes live.

**Comment by pjotrsavitski** [comment]
The images are live on the server.
