### ISSUE TITLE
Discount voucher

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#143]
Discount voucher will let players to earn rewards for completed activities.

New vouchers are added by admins or zoo admins by filling in voucher form:
![screen shot 2017-09-29 at 13 55 06](https://user-images.githubusercontent.com/380007/31013353-517fedc6-a51e-11e7-858e-61d11b1284e8.png)

Duration (h) shows how long current voucher will be active after earning it. Status states whether voucher will be displayed within dropdown under Activity.

Earned vouchers are visible for user under Profile.

Validating voucher is manual - opening earned voucher, confirmation button will be displayed. Clicking (tapping) on a button removes voucher under users profile.

**Comment by pjotrsavitski** [comment]
The initial functionality has been implemented. Any additions or changes should be handled within standalone issues.
