### ISSUE TITLE
Information activity item uses "Question" marker

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#145]
![screenshot_20171003-120328](https://user-images.githubusercontent.com/26867575/31120381-8672e024-a834-11e7-9bc6-9fb77c91f462.png)

I'm pretty sure they had a "!" icon before we proposed the change back in #115. The Information was to be excepted from the change.

**Comment by pjotrsavitski** [comment]
They had different icons for each question type instead. I am not sure what the issue is about though.

**Comment by PatriciaMoller** [comment]
The Information type was going to keep the !-icon, so it wouldn't be misunderstood as a question.

**Comment by pjotrsavitski** [comment]
This is the issue: #118 
It does not mention anything like that. Also, there was no SVG icon for the case, thus it should probably not have been so.

This is the state of the code prior to the commit that made the change: https://github.com/SmartZoos/Toolset/tree/64cc41767c3cf4d75b28e4900a37f975b970f2c5/public/img/icons/item

**Comment by PatriciaMoller** [comment]
It was written in #115, that the information marker was to remain.

I made new variants [here](https://drive.google.com/open?id=0BwI6ykFZVgBJS0VZbktPOWYzRGs) 
It had probably slipped my mind that it would have needed extra icons in order to be consistent with the rest.

**Comment by pjotrsavitski** [comment]
The out of reach icon seems to be having the question mark. Should that be so or or would it still have some other symbol?

**Comment by PatriciaMoller** [comment]
Fixed it.
