### ISSUE TITLE
Consider creating a Cookie Policy page

### ISSUE THREAD

**Issue by pjotrsavitski** [SmartZoos/Toolset#148]
We should determine if the is a need to create a Cookie Policy page with an explanation about the use of cookies (and other HTML5 technologies; as localStoreage and sessionStorage).

If there is a need for that, then it should be linked to from the general cookie consent element.

We might also mention that we use Google Analytics (that is also setting up some cookies).

It might be a better ida to have a general Privacy Policy page with section dedicated to Cookie Policy.

**Comment by PatriciaMoller** [comment]
Something that popped up: What about age? 
Facebook and Google have an 13+ age limit. Is that something we should consider as well? That could affect how school classes will use it, since children under the age of 13 will most likely.

**Comment by kaimikael** [comment]
Google and Facebook have restrictions since you might end up experiencing things unsuitable for children through their services, it shouldn’t be an issue in this game.

**Comment by pjotrsavitski** [comment]
If is considered a good practice. One of those has already made Privacy Policy a requirement for newly registered integrations.

It could become an issue in the future.

**Comment by pjotrsavitski** [comment]
Closing in in favour of #216, having separate Cookie Policy does not make sense. This will be art of the Privacy Policy document.
