### ISSUE TITLE
Featured activities

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#15]
Toolset activities view displays 4 featured activities with featured images and description of the activitiy.

To start an activity, "Start this activity" button needs to be clicked.

To see all public activities, "See all activities" needs to be clicked.

![screen shot 2016-08-17 at 12 08 45](https://cloud.githubusercontent.com/assets/380007/17730844/5c371a24-6473-11e6-9f3f-887346284378.png)

**Comment by kaimikael** [comment]
I don't understand this issue, @tammets, please clarify.

**Comment by kaimikael** [comment]
Ping @tammets .

**Comment by pjotrsavitski** [comment]
I suppose that this is about either determining some activities for the slider and featured line based on some algorithm (maybe even current user location) or offering the ability to set a certain number of activities as featured (this could be realised in numerous ways; certain amount per zoo; certain amount and the oldest featured is being removed when new one is selected; the system still tracks the featured flags but displays the N ones that were marked as featured last).

**Comment by kaimikael** [comment]
Hm?  What slider is this?

**Comment by pjotrsavitski** [comment]
I might have named that in a bit of a wrong way. Bootstrap call this carousel: http://getbootstrap.com/javascript/#carousel

Swaps images for some of the features activities.

This resembles the one that currently shows images on the front page: https://toolset.smartzoos.eu

**Comment by kaimikael** [comment]
I see, but I'm not quite sure where that fits into the proposed scenario, though maybe you have worked on further design with Priit?

**Comment by tammets** [comment]
It's just a landing page :)

**Comment by pjotrsavitski** [comment]
This functionality does not seem to be required any more.
