### ISSUE TITLE
Log in form

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#16]
Players are asked to register or to login for saving current state or sharing results. Playing a game does not require logging in.

![screen shot 2016-09-19 at 14 14 34](https://cloud.githubusercontent.com/assets/380007/18630178/6741535c-7e73-11e6-92b3-605d37976800.png)

**Comment by pjotrsavitski** [comment]
The form is not as fancy nor has social login possibility, but it does work: 8d356a5586319f6ee240cecb985a1ebdf5a819b8

Still needs to be fully hooked-up with translation system.
