### ISSUE TITLE
"Question Type" cannot be changed after creation

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#163]
When editing an already created Activity Item, "Question type" is locked and cannot be changed. 

Is there any reason for this?

**Comment by pjotrsavitski** [comment]
Yes, that is a feature. Multiple choice question should not evolve into Match pairs over time. Editing is for correcting mistakes only.

Changes to questions also affect any existing activities. Data is not being copied, just connected through relations.

Making a new one is not that hard either.
