### ISSUE TITLE
Language select propmt?

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#166]
Is it possible to prompt a language select?
Jens mentioned that the site by default being in English might become difficult for smaller children and other non-English speakers.
Since the language select on mobile is "hidden" in the menu, maybe it would be good to have an early clearly visible choice

**Comment by pjotrsavitski** [comment]
I would probably prefer to implement locale detection based on browser settings. Although, it might not always give 100% correct results.

How do you imagine the language select? Would it be a popover, tooltip or a modal dialog? Would that not be a bit intrusive?

**Comment by PatriciaMoller** [comment]
Locale based sounds nice, yes. But it could probably also cause issues with eg tourists from another countries.

A popover box would probably be a bit intrusive yes, but also very direct and clear. 
![language select](https://user-images.githubusercontent.com/26867575/32602669-457f6256-c547-11e7-9395-4a8993c44542.jpg)

Another option would be a landing page: (this is a very old example. Flags should be replaced by text):
![languageselect](https://user-images.githubusercontent.com/26867575/32602744-90102544-c547-11e7-94f3-4a72a4a29ba5.png)

**Comment by pjotrsavitski** [comment]
Locale is based on OS and/or browser language (even more complicated to be honest). For my case it should show either English or Estonian, even if I am at Skansen.

The popover/modal should only be shown on mobile devices with really small screen (phones).

**Comment by PatriciaMoller** [comment]
Oh, I misunderstood it as from geographic position. OS seems good.

How come it should only be shown on small screens?

**Comment by pjotrsavitski** [comment]
Easy enough. On bigger screens/higher resolutions (starting from iPad), the language choice menu is not hidden. So, it does not really make any sense to show that dialog.

**Comment by pjotrsavitski** [comment]
This is related to #168

**Comment by pjotrsavitski** [comment]
Language negotiation has been implemented. It might be sufficient to deal with the situation.

The implementation logic is trying to detect the best possible language, with fallback to English. This means that if the first preference is French, second one is Swedish and third one is English. The system should choose Swedish as it comes before English, but French is not a supported language.

**Comment by pjotrsavitski** [comment]
Implemented language detection seems to be working just fine and should be enough.
