### ISSUE TITLE
Creating Act. Items requires special permits?

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#167]
If a teacher wants to make a Activity for their class, they currently can't just make an account and make Activity Items. I was going to show the process of making an Activity to people at Skansen, but they couldn't make any questions because they were ordinary users.

I realize that this is something that was removed earlier in #122 and #124.

Is the only way to be given a Role with that kind of access to have an Admin give it to you?

**Comment by pjotrsavitski** [comment]
Yes.

That was discussed during the meeting in Södertörn and voted upon. These are specifically reserved to Zoo members and admins. Additional restrictions apply based on which of the Zoos that items belongs to.

There could be a possibility to allow normal users create those, but then we would be facing an addition of **status/state** to ActivityItem elements (and probably Activities). Those would be set to **draft** until reviewed by someone and only then become generally available.

That was related to the quality of questions and disallowing possible SPAM.

If that is an issue, then we need a general meeting and a new agreement (the decision is not mine to be made). Although, that would require some review system and resources to combat any possible SPAM.

**Comment by pjotrsavitski** [comment]
One more solution wold be to allow Zoo Administrator to assign Zoo Member role (according to what zoo he/she belongs to). Or even for normal users to make request for that role and someone to manage that. Yet that would still not going to happen very fast.
