### ISSUE TITLE
Present how/where to create Activity Items while in ActivityCreation

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#169]
The current "Add Activity" button seemed rather confusing to users. Both the phrasing ("Add") as well as using "+" indicated that it would lead to the Item creation, and not the "search and add" it actually is. The search box also has the header "Add Activity Item", which made them think instinctively think that it was a form to fill out, rather than different search criteria. This left them abit confused as to where they could create their own questions.

Either if it would be possible to create new Items from the Activity creation. (Show the Item creation in a Modal/overlaying box?)
Or the button and search box need to get their purposes more clearly presented. Maybe most easily by changing the name to "Search Activity Items" and/or use a search/magnifying glass icon, instead of a plus. In that case, the user must in some way be informed that the creating of an Item is done in another menu.

I was thinking of maybe having a link to the Item Creation, but not sure where. Since the user has to manually save, having a link takes them away from the form in the middle of creating could lead to losing unsaved progress. Maybe if it opens in a new tab? And then have them search for the Items they created?

Ties in a bit with #116

**Comment by pjotrsavitski** [comment]
Changing the icon + texts is a quicker way than moving Activity Item creation into this context (a lot less time consuming).

As for the creation of a new one. We could have some text and button that would open the Activity Item creation in a new tab.

Something like: "Did not find a question you are looking for? Go and create one."

If this solves the issue, then it is the way to go.

**Comment by PatriciaMoller** [comment]
Should the link show up before or after a search? I think it might be good to encourage using existing Items, to avoid clogging the list with too many similar questions. 

Two different suggestions:

Having the "Create new" option within the search. This puts using existing ones before creating you own. However, it you're set on making your own Item from the start, this might be rather tedious if you'd have to enter Search everytime.
![add in search](https://user-images.githubusercontent.com/26867575/32884854-fcaa50f2-cabb-11e7-89e7-734e25de4fdd.jpg)

Or
Having the "Create new" on the Activity creation page. This removes the clunkyness of going into Search everytime.
![new item on act page](https://user-images.githubusercontent.com/26867575/32885432-c859d7e4-cabd-11e7-9c82-01a4106b1858.jpg)

**Comment by pjotrsavitski** [comment]
I would personally vote for the first approach. I'd put the button on the same line as the "Search" one, just float it to the right. And maybe use different colour (the default button that looks grey should do well enough).

The reasoning is that it is not a place to start creating of new Activity Item objects. That is done within the specific section. This is just in case one is really missing something and solution allows to remove a few additional clicks.

As it happens in the new window/tab, after it is done, the person would need to search for the newly created item.

I think this makes the most sense. Also, permission checks would apply to it. Meaning, that if at some time the permissions are changed and current user does not have rights to create new Activity Item objects, that button will not be shown.
