### ISSUE TITLE
SmartZoos game modes

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#17]
- Suggestion-mode (based on users location, time, device and short questionnaire, spots will be generated. Unique to every player or team)
- Mission-mode (prepared tracks and gaming scenarions by zoos)
- Challange (player vs player, teams vs teams)

**Comment by kaimikael** [comment]
The team game mode has not been defined, we need an outline of it.

**Comment by kaimikael** [comment]
Ping @tammets , should we brainstorm about this?

**Comment by pjotrsavitski** [comment]
Are the game modes still on the table or should we get rid of those?

**Comment by kaimikael** [comment]
I think we can consider them as dropped.
