### ISSUE TITLE
"Description" should be placed below "Question type" in Act.Item creation

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#170]
Currently, the "Description" box is placed before selecting Question Type.
Since the content and purpose of the Description changes depending on Type, it should be placed after Type. Could the inputs for Answers stay where they are? That would make the flow of making an Item: 
Writing the title/main subject -> 
Choosing the Question type and thus context for how the description should be written -> 
Writing the question/info (and answers)

Perhaps an instruction/rename is needed for "Description" as well? Since it fills so many different purposes (Question or Information text) depending on context. Maybe "Question/Information"

**Comment by pjotrsavitski** [comment]
I see no issue with moving the Description input block.

The question details (answers) will stay where they are as they are part of the Type input block.

We could rename it to something more appropriate or could just add an explanation text below, the way it is done with Image.

One more idea would be to have some text as a placeholder. That could also serve as an explanation to what could the purpose of the input be (the way it is used with Access Code and Read more).

**Comment by PatriciaMoller** [comment]
A rename would probably be a good thing to do either way.
 
Placeholder text feel like a good, clean way to insert further instructions for the user.

**Comment by pjotrsavitski** [comment]
If you can come up with some name and placeholder text, then I could change the texts and move the input. It could also arrive with the next update (next week the latest).

**Comment by PatriciaMoller** [comment]
Is there any way to split the Question Type dropdown list from the the answer option input, so the Description block could be between them? Having the Description underneath the input was maybe a bit more confusing... 
![ai](https://user-images.githubusercontent.com/26867575/33420363-913cf8f8-d5ae-11e7-9a4a-60303d63cd27.jpg)
Sorry, I was a bit unclear

**Comment by pjotrsavitski** [comment]
It could be done, although it does not make much sense as the type choice and question options are in essence bound together and form a logical block.

**Comment by PatriciaMoller** [comment]
This was something we noticed when trying to make Act. Items with educators at Skansen. We believed that having a flow more similar to the way it's presented to the player would make it more readable. 

Before the flow was: Write Question -> Choose question type  -> input answers.
With the flow Choose type -> Write Question -> input answers, you early on establish the context the rest of the content will be. For someone who hasn't used the tool before, they would be able to see the different options before they start writing. Otherwise, if they just blindly started filling in the boxes (which could happen) they might have to back and fourth because  what they wrote in the Description no longer works because they wrote the question without the context in mind.

"Description" could be renamed to "Question/Info." That would tie in to the placeholder text, which does enough to solidify what box is for.

**Comment by pjotrsavitski** [comment]
Please do create a new issue for that then. It should arrive soon if that does not have any implications.
