### ISSUE TITLE
Header Images added to Activity cannot be removed

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#172]
Currently if an image has been added to an Activity, there is no way option to remove it.

It would probably be good to be able to do that, in case the user changes their mind or must remove it for some reason.

**Comment by pjotrsavitski** [comment]
Well, never though of it that way. I could add a checkbox to allow that. If the checkbox is checked and no new image is selected, then the previous one would be removed.

**Comment by pjotrsavitski** [comment]
Just to make sure. Did you mean an already uploaded image or just a chance to clear the image input within the form (not submitted yet)? Or both?

**Comment by PatriciaMoller** [comment]
Both, now that you mention it.

The original post was about already uploaded images.
However, you can't clear the input either. It would be nice if you could clear it, so you don't have to save it and go into edit just to remove the image

**Comment by pjotrsavitski** [comment]
Thought so. I suppose it should arrive tomorrow as it is not really a big deal.
