### ISSUE TITLE
Make start page more informative

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#175]
The current start page does not inform the player/user about what to do.
The "Register" and "Login" button in the "What is SmartZoos?" box attracts attention but never really says WHY you should do any of them. (Information of the purpose of an account could be on the register page as well)

Suggested info/headers to be on the Start page:
"What is SmartZoos" A description of the game, rather then the project
- "SmartZoos is a location-based game service, where the activities will guide you throughout your environment and teach you a thing or two." 

"SmartZoos for Schools"
- "Move the classroom to the great outdoors!
SmartZoos is a modern way to combine school with gamified fun. With a Creator account, you can create fun and activities to be used by you and other SmartZoos users"
Here, there could be a log in/Register button.

The current text in "What is SmartZoos" could either be in a seperate "About" page or at the bottom.

**Comment by pjotrsavitski** [comment]
The ending with "other SmartZoos" sounds strange. I'd say just "others" would probably be better.

As for making changes to the front page, I think that makes sense.

We could also have a section that shows some numbers (if needed). Something like "that mane activities", "that many registered users", "that many games played" and so on. Although, that could just be a bunch of excessive information.

**Comment by PatriciaMoller** [comment]
Typo. Meant to write "other SmartZoos users". Fixed.

I think it might just be excessive with numbers. At least in the beginning. If SmartZoos takes off and gains a lot of user/players then, sure it'd be nice to show that off. I think information about what the app is and how to use it is more important at the moment.
"No. of times played" could maybe be something for filtering/sorting Activities. "More views = Better"
