### ISSUE TITLE
Facebook and Google login on Register page

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#176]
Since a new player would probably go to "Register" before "Log in", it would make sense to have the FB and Google login options there as well. Otherwise they would go unnoticed.

**Comment by pjotrsavitski** [comment]
These could be added, although it is not a registration (in its purest form), it is a SSO (Single Sign-On) solution.

One more possibility would be to move the link to registration page under the login. That would require one more click for the action, but would allow to keep the registration page "cleaner".

**Comment by PatriciaMoller** [comment]
I tried to come up with some alternative, but didn't feel quite happy with any of them.
![login v2](https://user-images.githubusercontent.com/26867575/33177690-cfdda0ee-d063-11e7-898f-b8e18c1c0935.PNG)
This one has the more discreet, ordinary link. This might work better on desktops, but how it feels on mobile is more important, since I'd believe most user will login for the first time on their phones.
Could the contents in the email/password boxes the sent to the register page? To avoid having the user to write the same thing twice if not necessary.

**Comment by pjotrsavitski** [comment]
Yes, that is possible. Although this page seems a bit strange, I mostly mean the "Sign in with e-mail". It is not a button and will not really trigger the process, the "Log in" button will.

We might try to show the user that creating a local account is also a possibility. The "Register Account" link will probably be ignored in currently proposed solution.

We should change the text within this page, it no longer is accurate. We do not have any puzzle pieces. We do have badges and vouchers instead.

**Comment by PatriciaMoller** [comment]
![log-in-rehaul](https://user-images.githubusercontent.com/26867575/33420775-23980b06-d5b0-11e7-8ec2-1276085132d7.gif)

This is a Gif of a slightly different version, where the register link is a button instead. 
But the main thing is that the email/password boxes would be "hidden" until you press the button, to minimize the initial clutter. If you want to use email, only then are those boxes relevant to you.

If having a button instead of a "Register" link, then the content of the email/password should carry over to the next page.

**Comment by pjotrsavitski** [comment]
We could try this approach, though it could mean that almost not accounts would be created without FaceBook or Google SSO (that is not a big deal though).

**Comment by pjotrsavitski** [comment]
Content of the password will not be carried over to the next page, only email. The password will only be part of the form and will not be passed forth as a query string parameter. Other parties could save the contents of the URL, even if encryption is enabled.

**Comment by PatriciaMoller** [comment]
Are there any positives to make an email account? Or would all the accounts be treated the same?

Ah, that makes sense. Hopefully, re-writing the password won't be enough to make them not want to create an account at all.

**Comment by pjotrsavitski** [comment]
Any account is a local account, in the end. The difference is within the login procedure. Local accounts require password, SSO accounts only require password if the user is not yet logged in with the service provider.

Most would probably choose either of those. Unless someone really wants to create a local account.
