### ISSUE TITLE
A link from the projeect website to the Toolset?

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#177]
Should there be a link on the smartzoos.eu page to the Toolset start page? In the case of someone inputting the wrong URL. 

As the project wraps up, a banner for links to the Toolset could be made.

**Comment by pjotrsavitski** [comment]
But if you would like the banner with a link to be present. Please send me one. I could update the project web.

**Comment by PatriciaMoller** [comment]
There is no banner yet, it's something @Pnella could get to as the the project wraps up. 

I was for now mostly thinking if there should be a referral to the Toolset, but maybe it's a bit too early for that. I remember back during spring, some testers ended up getting to the project site and felt a bit lost. But the QRs might have fixed some of that.

So. I guess this can disregarded, since the URL is planned to be changed anyway.

**Comment by pjotrsavitski** [comment]
We could put that to the index page, using one of the images from the ones you have emailed.

There should probably be some text that accompanies the images.

We could even host the logic back on the platform itself: either provide an endpoint that could be embedded within an <iframe> or provide an HTML code piece that could be added to any web page. This should remove the need for hosting the image and would make adding that somewhere a rather simple task. That could later on be used by the Zoos and others, if even proven to be required.

**Comment by PatriciaMoller** [comment]
Updated Banner Illustration [here](https://drive.google.com/open?id=13uKZrvjCjn4U1kq_0WBorjgcndxj5iQP)

**Comment by pjotrsavitski** [comment]
We have changed the addresses of the project web and toolset. Toolset now resides within the top level domain. Closing the issue.
