### ISSUE TITLE
Make Act. Items with Access Code marked as clickable even if out-of-reach

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#178]
If an Act. Item with an Access Code is out of reach, it should in some way be marked as intractable.
However, making it orange like an Item within reach would remove the use of colored/grayed-out icon.
Suggestion is to make an alternate grayed-out icon

**Comment by pjotrsavitski** [comment]
I could add the icon when it is ready.

**Comment by PatriciaMoller** [comment]
I made 2 variants: 
A "Lock" icon. The orange would indicate that it's still clickable, and thus encourage interaction. However, the lock might "scare" the player away from interaction, since it might suggest that it has to be unlock before it could be interacted with. 
![lock](https://user-images.githubusercontent.com/26867575/33717839-ad3d2c8c-db5b-11e7-8ea8-cd1cc3c0af01.PNG)
Found [here](https://drive.google.com/open?id=1o9Srpae6XmnYd5nFOp0lm11jBt_OFDCD)

A variant of the current info/question icons with a smaller lock. Since these look more likte the usual ones, player might be less hesitant to interact, but is the lock is very small and a bit hard to see. So I think the first one is better to use.
![lock2](https://user-images.githubusercontent.com/26867575/33717841-ad898988-db5b-11e7-8b90-c0af4dc8c289.PNG)
Found [here](https://drive.google.com/open?id=12ruCQvy3-0hTu077_FVQH-ftOWp7GLtU)

**Comment by pjotrsavitski** [comment]
I am fine with both icons. Information has its own special icon. Will we also do the same in this situation or should the general one be ok?

**Comment by PatriciaMoller** [comment]
If you use the ones where the !/? are visible, then they should be different, to maintain consistency.
Both versions, one for information and one for questions, are available in the links in the post.

**Comment by pjotrsavitski** [comment]
I'll go with the second variation. It has both images and is has a distinguishable symbol for the item type.
