### ISSUE TITLE
Access code clues input

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#179]
It'd be useful to have some way to give clues to what/where the Access Code is. In case there are no obvious signs in the real world.
However, game design-wise, this may cause an issue of it feeling like there are two questions instead of one.

**Comment by pjotrsavitski** [comment]
Well, the location depends and could even change. it might not even be a code that could be seen somewhere, but something that the person would come up with while being at the spot.

We could have another text for the clue, but it will just be in one language and would be stored within the database.

**Comment by PatriciaMoller** [comment]
We were a bit concerned about the maintenance of the codes, if there were eg stickers or so. They would be as likely to change as any other element.

We figured that since Activity/Act. Item has a set language, the clue's would only have to be in that language. It would only have to change if the any of the other do.

**Comment by pjotrsavitski** [comment]
Yes, that could also apply. But please do think it through as adding clue to the form is just part of the puzzle. The other one would be displaying it within the modal. Plus, the creator might decide to leave that one empty.

**Comment by pjotrsavitski** [comment]
Please specify what kind of input are we dealing with: either simple one-liner or a multiline textarea, then it could be implemented.

**Comment by PatriciaMoller** [comment]
A one-liner should be sufficient

**Comment by PatriciaMoller** [comment]
The Code and Clue line should switch places in order to have the same flow as writing the question
