### ISSUE TITLE
Repository of questions/tasks

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#18]
Every registered user can add location based questions or tasks that can be used for generating tracks / missions for players.

Question or task is described as follows:
- Title
- Description / question
- Question type
-- One correct answer
-- Multiple correct answers
-- Match pairs
-- Embedded content
-- Photo
-- Information
- Location (on a map)
- Zoo
- Language

![screen shot 2016-11-22 at 10 47 57](https://cloud.githubusercontent.com/assets/380007/20516862/365d2260-b0a1-11e6-980b-5d2505c8982c.png)

![screen shot 2016-11-22 at 10 48 01](https://cloud.githubusercontent.com/assets/380007/20516870/425049da-b0a1-11e6-87fa-267d1e40d625.png)

![screen shot 2016-11-22 at 10 48 04](https://cloud.githubusercontent.com/assets/380007/20517019/da4ab6e4-b0a1-11e6-9d01-fee01da8d0c6.png)

**Comment by pjotrsavitski** [comment]
Forgot to reference from this commit cc4a7e9ced084367fbaa06ffee936a59fd7ef85e

**Comment by pjotrsavitski** [comment]
Forgot to add reference to a few commits:
652cbd2b08eec7055184412afb149ab86b92b97b
46ebef952d6d05b58e1df68abe7694a5c4c6c1d8
5e90457b03b80e7082b0894f3f399076df0e935a
d111ca62fe72e08693987161b27bed89f498abe7

**Comment by pjotrsavitski** [comment]
This one is good enough, closing.
