### ISSUE TITLE
Make access code non-key sensitive

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#180]
To simplify code input, since some phone keyboards automatically make the first letter capital.
It would also minimize confusion, if they're consequently written with small letters, when codes were written in real life.

**Comment by pjotrsavitski** [comment]
Will it be enough if the checker mechanics compares these after converting both to lower case? That will have to be done in any case, as the user input would also be affected by it.

It could also be done before writing it into the database, but that does not make too much sense. Comparison system is part of codebase and could be tuned at any time to fit any needs.

I would go with this solution for now as it seems most meaningful of available choices.
