### ISSUE TITLE
Submitting photo refreshes page

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#185]
When attempting to submit photo in a Photo Act. Item, the page refreshes and makes you unable to progress. Item remains unanswered, even when logged in. I guess that is because you never press Submit

![photo reloads](https://user-images.githubusercontent.com/26867575/34249134-e133bb72-e638-11e7-9a66-2eb5b69838a6.png)

**Comment by pjotrsavitski** [comment]
I will see about that. There was a JS Error in in the logs. There might be an issue with the code.

Does it open the image with a size that prevents pressing the Submit button or does the page just become unresponsive with no way to submit an image? Any hints on the OS. Just want to understand what happened and how to reproduce.

**Comment by pjotrsavitski** [comment]
I suppose that the OS could have been a Firefox. I've checked the report and was able to identify the issue in Firefox. Fixed the code as it should have passed the event explicitly from the start. Not sure why none of the other browsers were affected. The update should arrive into the server in a couple of days. I will notify you and the issue would only be closed once you have made sure that everything is working as expected.

**Comment by PatriciaMoller** [comment]
I tried the Photo item on my phone (with the built-in "Samsung Internet" browser) but it still refreshes the page. I tried both when logged-in and not.

It works on Firefox on desktop.

**Comment by PatriciaMoller** [comment]
When testing on an iPhone 6S, iOS 11.2.5, the photo added but the modal box extended pass the screen making the buttons unreachable. Attempting to scroll the box instead moved the map behind it.

![image-1](https://user-images.githubusercontent.com/26867575/35568306-cb74789e-05c8-11e8-9120-3f0f33607285.jpg)


Should the camera picture perhaps be replaced with "Re-take picture button to take up less space. Maybe also be but below the picture.
