### ISSUE TITLE
Warn non-logged-in user if trying to play

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#188]
There is currently no way while in-game to if you are logged in.
As progress can only be saved if logged in, warning the player that they are not logged in before they get into playing might be good. Maybe as part of startup, in the cases were there are no vouchers? (Granted that Act.s with voucher will get a prompt, as concepted in #150) Or as they press Play, before switching over to the game page.

**Comment by pjotrsavitski** [comment]
We could have some dialog or just a native "confirm" element with some notice about playing without logging in, after play button is being pressed.

The description does differ a bit from the title of the issue. If that is needed, we could add an element to the top menu bar of the game that would should the user if authentication has happened or not (although, it would already be too late, as anonymous games would stay anonymous).

**Comment by PatriciaMoller** [comment]
Some kind of "You are not logged in! - Progress will not be saved and any rewards cannot be claimed." when pressing the play button would be good . Preferably a modal box so it can be customized with art later on. 

Yes, the title should have been more like "Warn non-logged-in user if trying to play". The issue is more prominent on mobile since the Login menu item is not visible at first glance.
