### ISSUE TITLE
Have title of ActItems out of reach show up when pressed

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#189]
Similarly to how "It's you!" pops up when pressing the player icon, the title of the Act. Item could who up when pressing it on the map. And then disappear as you press outside of the Item icon.

This to add interaction feedback as well as act as a hint to what/where the Item is placed. Part of user guidelines would have to be make titles short and concise, so these blocks of text don'r end up being too big 
![harardu](https://user-images.githubusercontent.com/26867575/34259953-79796532-e664-11e7-93db-464bdea43655.PNG)

**Comment by pjotrsavitski** [comment]
Even bigger texts should not a really big issue. The element that shows the text is called InfoWindow and it is able to hold more that just one line of text.

If it should only affect the "Out of Reach" items, then there could be an issue with "access code" functionality. In case some item is unreachable, it would open up the access code (if present) and not the InfoWindow.

If that is not a big deal, then this feature could be implemented.

**Comment by PatriciaMoller** [comment]
I think it would okay if the access code window show up.

Alternately, it could have an "Unlock?" button. I will sketch a bit on that.
