### ISSUE TITLE
Task / question description can involve embedded content

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#19]

**Comment by kaimikael** [comment]
I only now got the point of this :-)  Yes.

**Comment by pjotrsavitski** [comment]
There currently is a special type of question for the embedded content.
Do we still need the description to allow embedded elements? Currently the logic is that description allows PlainText and HTML will not be allowed (it would be stored, but rendering will escape it and make useless).

**Comment by pjotrsavitski** [comment]
Current solution does not allow that. Embedded content could be placed in a special field. Please make a new issue if this is proven to be needed in the future.
