### ISSUE TITLE
Close tab/window after creating Act.Item via Act. creation?

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#190]
Extension to #169. Currently, when saving the Item you are taken to the Item's "page".

Suggestion is, if you are making an Item from the link in the Act. creation, the Item creation form could open in a separate window. One of those scaled down ones, with only the address field:

![create popup](https://user-images.githubusercontent.com/26867575/34262347-71ea9b3a-e66c-11e7-85d3-4432b6684301.png)

After creating/saving, the window will inform the user that the "Activity Item has been created. Add it by using Search Activity Item". Then window closes by either a "Close this window" button or just closing it as usual.

**Comment by pjotrsavitski** [comment]
Content from one window does not generally affect the other. This solution would need to whole form to be added into the flow of creating an Activity. Opening a smaller window would not really work well on any handheld devices.

I could take a look at it to make sure what the possibilities are. But it would require a deeper integration for that to be working the way it is described here.

**Comment by PatriciaMoller** [comment]
What do you in this case mean with "Content from one window does not generally affect the other". I don't see how this is much different from opening the form in a new tab? The created Item would still need to be added manually. 

For mobile devices, it would still need a new tab, but would a "close and return" button still be possible?

Having a Item creation option in the Act creation streamlined the process but containing the steps to one form. However, when pressing "Save", you are taken to a ".../activity_items/xxx" page. And thus "out" from the creation process. The page you get to has no information of how to later on add it to the Activity. I believe that this way would make the process more clear to the user.

**Comment by kaimikael** [comment]
A comment:
I got confused when creating an activity—I filled in the info and then pressed **Create new Activity Item**.  This did open a new tab, while the ongoing Activity creation remained hidden behind the new tab without me noticing.  This is consistent behaviour, by all means, but at least on my phone (a Sony Experia), the feedback indicating the new tab opening is very subtle, so I missed it.
Given this it does make sense to close the activity item creation tab once the item has been created, thus returning the creator to the *ongoing* activity creation process.

**Comment by PatriciaMoller** [comment]
@kaimikael Yes, that's pretty much the thought. I noticed while testing/showing it that the user got slightly lost after pressing Save on the Act. Item. As there is no indication for you how to get back to the Activity creation.

Having a button to create an Item from the Activity creation made it quicker and easier to get to that part. Now we just need a quick way back.

**Comment by kaimikael** [comment]
Right.  I suggest that creation of the activity item will also close that tab, then the user should automatically return to the prior tab.
