### ISSUE TITLE
Make divide between different activities in list clearer

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#191]
While testing, we noticed that some users were about to press the Play button for the Activity above the one they intended to play. I think an effective solution would be to put border/dividers between them 
![activity list med borders](https://user-images.githubusercontent.com/26867575/34405459-d0b98f4e-ebb3-11e7-9496-d9d254d77ce1.jpg)

**Comment by pjotrsavitski** [comment]
This seems to be a meaningful solution. Another one could be the relocation of the Play button (or we could think about it and implement, if any good solution is found).
