### ISSUE TITLE
Remove link to Discount Voucher for non-admin users

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#193]
Since only admins are able to create and manage Vouchers, the link should be removed for other users. Similar to how the Activity Items menu shouldn't be visible for non-logged (and later on, ordinary users)

**Comment by pjotrsavitski** [comment]
This would mean that we could not link to the page with vouchers from any place, but the whole information about attached voucher should be shown as part of the view for other content type (pretty much Activity) + within the game.

I suppose that I have currently left the links in there, although the full information is also being shown.
