### ISSUE TITLE
Make Exit Activity button when finishing Activity go to activity list

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#194]
Mentioned in #101.  Have the Exit button in the Results lead to the Activity list, instead of home page.

Something seen in many level-based games, you will return to the same place in the menu as you were when you entered. In this case, returning to the activity list to promote further play. 
However, this might require that filtering options are retained. As in #186

**Comment by pjotrsavitski** [comment]
I suppose we could store the URL of the page that started the game process. With fallback to listing index with no filtering options.

**Comment by PatriciaMoller** [comment]
If possible, that would nice! And if so, then perhaps the same method could be used for #186 as well?

**Comment by pjotrsavitski** [comment]
I will check it out. The solution might need t be perfect as there are other ways to get into the game, a few examples would be: resume or go to see the results from the dashboard, just paste the URL into the browser, open using the QR code.

Any of those would default to the normal listing. That could still be better then the main URL.

I will have to thing about the best and least intrusive way to get that implemented. I already have some ideas, but it would need some checking.

**Comment by PatriciaMoller** [comment]
Oh, right, didn't think of the alternate routes. Getting back to a neutral list seems most reasonable, though then I think the Location filter should be more prominent so the user can narrow them down quicker.

I think I have to sit down a properly sketch out the flow for this
