### ISSUE TITLE
"Complete" image for when finishing activity

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#195]
In order to make a more celebratory ending, an image could show up before the current results screen. 
CSS Animation:  In- jackInTheBox. Out: fadeOutDownBig
![complete in context](https://user-images.githubusercontent.com/26867575/35561841-d46c2814-05b1-11e8-9189-8bae49d92b0b.png)

**Comment by pjotrsavitski** [comment]
The issue with this example is that it has 100% on it. This could only fit the case of all questions being answered correctly.

The images should also look good on every screen.

**Comment by PatriciaMoller** [comment]
Updated Complete illustration can be found [here ](https://drive.google.com/file/d/1KgS2dbvYSJIWF5gtCXo1uPE5FTG1ssqA/view?usp=sharing)

**Comment by pjotrsavitski** [comment]
Should it be removed automatically after some time or would it require a click/tap?

**Comment by PatriciaMoller** [comment]
Hmm, automatically I think.
But could it also be clickable, so you could move forward faster?

**Comment by pjotrsavitski** [comment]
Yes. Combined approach should be doable.
