### ISSUE TITLE
Game does not progress after when submitting last answer when logged-in

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#196]
When logged-in, pressing the submit button on the last question does not make the modal box close and results appear.
Instead, the button gives the "pressed" feedback, and then seemingly does nothing.
However, refreshing the page/game immediately shows the results. So it still submits the answer. This happens both when the Activity has a voucher or not. If a voucher is attached, it is not rewarded. I'm guessing since it never properly gets to the actual rewarding step

When logged-out, it submits the last answer as intended.

Tested on both desktop (Firefox & Chrome) and Android (Samsung Internet, Chrome)

**Comment by pjotrsavitski** [comment]
I would guess that there could be some bug in case a voucher is going to be assigned. Something goes wrong and the response from the server is not received. Could be due to one of the last changes related to vouchers. It will currently be at the top of the issues list.

**Comment by pjotrsavitski** [comment]
Confirmed, we are dealing with a bug that happens with higher tears of badges. Will go through the logs and the code and confirm that nothing else is wrong with it. The update should arrive soon enough (would be directly updated into the server).
