### ISSUE TITLE
Make Badges page more informative

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#197]
Currently, the "Badges" page lists all the available badges within game. But without any real context. 

Suggestion:
-Have an "introductory" text for them. Something like "By accomplishing certain tasks within SmartZoos, you will be rewarded with badges. The badges you have collected can be seen on your Profile [link to profile]".
For non-logged in users, add ~"In order to collect badges, you must be logged in [link to login/register]"

-Only show the first tier of each series of badges. Seeing all of them might spoil the growth of each badges.

**Comment by pjotrsavitski** [comment]
A small issue is that badges themselves do not really know about the tiers (these are not really related in any way). The code that awards them know a thing or two about that.

I could create a list of badges that are omitted from that page, if that is required.

**Comment by pjotrsavitski** [comment]
I've checked the code. As we are using the OpenBadges integration, we do need a unique page URL for each badge (that is the spec requirement).

I have not made a separate page for each badge, but used a unique identifier to be able to force listing page to be scrolled to a certain badge and that to be displayed.

This would currently prevent us from removing any badges from the listing without rolling out another solution for that purpose.
