### ISSUE TITLE
Should a user’s email address be checked at registration?

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#198]
Currently we do not check the email address for validity (nor that it actually belongs to the user) when a user registers with an email address.  Could this become an issue further down the road?

**Comment by pjotrsavitski** [comment]
It could become an issue if we want to notify users by email. The message would either be sent to the wrong person or outright incorrect address.

I would also guess that most registrations would be made with either Facebook or Google.

Yet we could enable validation of email before enabling the account (local one) if that is required

**Comment by kaimikael** [comment]
I'm thinking that if we say “give your email address” rather than just “pick a random username” we imply that we’re eventually going to use that email address in some way and in that case we probably should make sure that the address works and can be accessed by the user.
On the other hand I prefer simple and streamlined registration processes.  Do we foresee a situation where we actually need to send messages to players?  (I assume that this also goes for those logged in via Facebook or Google.)  If not, maybe we could drop the requirement for an email address and just ask for a unique user name.

**Comment by pjotrsavitski** [comment]
Well, email is being used for password reset. That one is applicable to local passwords and is not really of much concern to the SSO users. So we are probably unable to get rid of it.

We could start validation email addresses on registration. But that has to be considered.

There could be some cases we can not currently come up with that could require communicating with the user. Email address seems to be the only option we currently have.

**Comment by pjotrsavitski** [comment]
This will be implemented before the service goes public. This is not a very high priority, but will be tackled as soon as all the important things are done.
