### ISSUE TITLE
File selection should be restricted beforehand

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#199]
The **Choose file…** dialogue for adding images to activity items allows selecting video and audio files, even though they aren’t accepted.  The `input` tag should be supplied with an `accept` attribute to prevent the user from attempting to upload invalid files.

**Comment by pjotrsavitski** [comment]
I suppose we could just use the “accept” attribute on the file input. That should allow jpg/jpeg and png. This should keep other files being gray.

**Comment by kaimikael** [comment]
Yes, exactly.
