### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#2]
SmartZoos toolset can be used in English, Finnish, Swedish and Estonian. Toolset supports users to choose preferred language at any time.

Content of the games is is not translatable.

**Comment by kaimikael** [comment]
Translatability of questions is an interesting point – it seems that if we are supporting multi-language playing, we also need to have multiple versions of the questions.  Assuming we have a network of zoo people, could they support each other by helping out with translations?

**Comment by pjotrsavitski** [comment]
I would stick to interface translatability as part of the main flow.

If content has to be translated, then it is a separate issue and should be defined early on, otherwise the system logic could require more complexity on later stages of development (might have consequences).

**Comment by kaimikael** [comment]
I'll toss out a question to the zoo people about how this should be handled.
