### ISSUE TITLE
A more explict "How to play" image during start up.

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#205]
If the first marker is way outside the screen, players have been confused about they should be doing. An image depicting gameplay ("Follow line to maker, press maker") should be the first of the current tutorial images.

Illustration coming soon

**Comment by pjotrsavitski** [comment]
It should not be an issue to add more images to the slideshow.

**Comment by PatriciaMoller** [comment]
Illustration available [here](https://drive.google.com/file/d/1yLaWzM6bBOmAO9v3P35_YIVoPkjteTKt/view?usp=sharing)

Text Suggestion: "Investigate the location and find all complete all the tasks!".

**Comment by pjotrsavitski** [comment]
I will try to get that implemented as soon as possible. That is a simple change and should not introduce any bugs. Expect that to arrive today, in the evening the latest (it could arrive earlier, if it will be an independent update).

I suppose that suggested text has a typo in it, it should be: `Investigate the location, find and complete all the tasks!"`
