### ISSUE TITLE
Be able to see correct answer after answering incorrectly

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#207]
The player would want to be able to see the what the correct answer was if they had picked an incorrect answer. So that they don't have to wait until the final results (it's not guaranteed that they will play so far)

Either if a modal box of the question shows up and/or the marker is clickable, showing the answer they picked and what was correct.

**Comment by pjotrsavitski** [comment]
If this is crucial, then I would try to put that at the top of the list and solve it as soon as possible.

There are only two question types where one could give incorrect answer: single choice and multiple choice. Should only those be considered or should it work for all the question types? Others would just show the given textual answers (match pairs and information do not really have anything to show).

**Comment by PatriciaMoller** [comment]
It has been brought up by some of the zoo educators, and yes, it's something that would be very useful.

Single and Multiple are the ones that should have that immediate feedback.

The others could only be clickable, so the player can check/remind themselves of what they submitted. Though that is less important than the seeing the single/multiple answers.

**Comment by kaimikael** [comment]
But note that this is in contradiction to issue #208.  If we show the correct answer immediately after a wrong answer we can't also offer the chance to answer again.

**Comment by PatriciaMoller** [comment]
Okay, maybe not immediately. But after the last attempt.
