### ISSUE TITLE
Map view resets to user’s current position

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#209]
I’m uncertain is if this is intentional or not:
I press the “drop” icon to show all the questions in one view.  After a random interval the view will revert to put my current position along an edge of the view.  (This is probably exacerbated by me sitting in Huddinge, trying to look at questions at Skansen.)
I think the view should remain where it is until I make an active choice to move the view.

**Comment by pjotrsavitski** [comment]
I will have to check it out (just in case there is a bug in the code). But it could be related to another feature of **tracking position**.

If tracking is enabled, then the map will be reset to user position as soon as new positioning data arrives.

**Comment by pjotrsavitski** [comment]
Ok. I can confirm that happening. This is clearly a bug. I will make sure that it gets fixed. Not sure about today, but will surely happen tomorrow.

**Comment by pjotrsavitski** [comment]
I have a lead to why it is happening. If you have the time (it does not take too long to produce this effect). Could you try to observe this behaviour with leaving the InfoWindow with **It's you** text for the user current position open, then open the. Then do the same with closing the InfoWindow first.

I am pretty sure that it will happen in the first instance, but should not happen if the InfoWindow is closed.

This should be the source of the issue: https://developers.google.com/maps/documentation/javascript/reference/3/?csw=1#InfoWindowOptions

I checked our own codebase and did not see any bugs with position tracking code and could not find anything. This seemed to the the case when this odd behaviour occurred.

**Comment by pjotrsavitski** [comment]
Thanks for checking it out. This confirms my own observations. I will push the fix to the server tomorrow.
