### ISSUE TITLE
Tip page lost?

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#218]
Seems like the tips page at the beginning of the game disappeared this morning?

**Comment by pjotrsavitski** [comment]
Just checked it out in the Toolset. The tips page is shown.

The logic is that it will only be shown once per session (session would end once the browser is closed). If someone plays one Activity and then starts another one, then tips will not be shown as the Session Storage would have a certain key set.

**Comment by kaimikael** [comment]
Ah, I see.  Hm.  I guess that makes sense.  Let’s keep it that way and see if others also get confused.
