### ISSUE TITLE
Set up database server

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#22]
Prerequisite to task #18 
We need a database to store game questions.  This has to be installed and configured.  
We should use a server in the smartzoos.eu domain which is accessible for all zoos.

**Comment by pjotrsavitski** [comment]
This one brings the whole package, including the database connection possibility, database connection configuration and much more.

Database server is already a part of the virtual host environment (we are planning on using MySQL; although Laravel should be ready to run Postgres with no modifications needed).

**Comment by pjotrsavitski** [comment]
Virutal hosting takes care of this one.
