### ISSUE TITLE
Un-resourced string

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#226]
I noticed that when creating an activity, the language choices are all in English, even if I have Swedish as the browser.  See attached screen shot.  I expected the menu would use the language strings in 'languages' in resources/lang/sv/general.php.

![screenshot_2018-04-20-14-45-47](https://user-images.githubusercontent.com/10616212/39051751-f99d5022-44a9-11e8-89e2-a909ef0c0bd3.png)

**Comment by pjotrsavitski** [comment]
This is because  "language select" and "system language select" use the same translations. Try switching to "Estonian".

If all the language names are translated, then it should work as expected.

**Comment by kaimikael** [comment]
Do I understand you correctly that this set of language strings comes from the phone OS and is not anything we can affect?

**Comment by pjotrsavitski** [comment]
No, that is because of translation file contents. Compare those:

https://github.com/SmartZoos/Toolset/blob/master/resources/lang/et/general.php#L25
https://github.com/SmartZoos/Toolset/blob/master/resources/lang/sv/general.php#L25

Estonian has translations for all the languages, swedish one has texts (translations) in native languages. Language select (input element within a form) and platform interface language select both use the same place from translation file. This is why you get that kind of result.

**Comment by kaimikael** [comment]
?  No, I don't understand at all now.
The Swedish resource file says 
   'languages' => [
       'en' => 'English',
       'et' => 'Eesti keel',
       'ru' => 'По-русски',
       'fi' => 'Suomi',
       'sv' => 'Svenska',
   ],

so I expected the ”Språk” menu above to show “Svenska”, not “Swedish”.

**Comment by pjotrsavitski** [comment]
Well, that is strange. I just switched language to swedish an visited the same page. It had what you would have expected.

The language option did not come from the browser setting, I switched manually. But that should have no difference what so ever.

**Comment by kaimikael** [comment]
How interesting.  Hm.  Maybe it does have something with the OS to do, because I set the _browser_ language settings to Swedish, but the rest of the phone still speaks English.

**Comment by kaimikael** [comment]
This is in Chrome on an Android, just to be clear.

**Comment by pjotrsavitski** [comment]
I could check it out later, with system setting the language, not manual select. See what I get, but I have doubts it would matter.

Maybe something is tying to translate the page, at least partially. But this one is just a wild guess.

The translation system is the same for all the interface. Thus, it should not be different at all.

**Comment by pjotrsavitski** [comment]
It is a bug, have finally identified it. The issue only appears when the local is detected automatically. Language options logic is used for determining the language. But that is loaded/initialised before the language is set.

Will provide a fix soon.
