### ISSUE TITLE
Define database structure

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#23]
Prerequisite to task #18 
The data structures for the question and user databases have to be defined.

**Comment by pjotrsavitski** [comment]
Initial database structures come from commit 7a8ec82add4b7789fb8f4cd72b5a79f3aa5d7ab0

**Comment by pjotrsavitski** [comment]
This one really depends on the concrete object types. These should be tackled within the concrete issues (hard to define structures without clear definitions of types and connections).

**Comment by pjotrsavitski** [comment]
These will be defined as needed.
