### ISSUE TITLE
Select target set for a game

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#24]
Depends on #18 
Pick a set of targets from the target database.

**Comment by pjotrsavitski** [comment]
This one is simple, once we get the targets. It also needs some logic on how to search for targets and then add these into the game. UI side solution.

**Comment by kaimikael** [comment]
Not necessarily a UI side solution as such.  The point is that there is a set of targets, and we select a random subgroup of them to present in the game.

**Comment by pjotrsavitski** [comment]
This depends on availability and would need a logic of selecting to be attached. Probably, a story issue at first and only then a development one. These stories could also be attached to certain milestones. I would either repurpose this issue or create a new one, a lot more specific (will leave this one still open).

**Comment by kaimikael** [comment]
The selection logic should be as outlined in section 6 of the storyboard document:

A “mission” consists of p = m×n “targets” (as a rectangular number allows us to cut the award picture into simple shapes (rectangles)—9, 12, 15, 16, 20 probably being the sensible choices). The difficulty of a mission can be adjusted both by changing the number of targets as the difficulty of the questions themselves.
A zoo will define a number of points as potential targets, where interesting questions can be asked. Each target should have several alternative questions at multiple difficulty levels.
A mission selects p targets and a question for each target. The target questions can be answered in any order.

**Comment by kaimikael** [comment]
This by the way also goes some way towards defining the requirements for #23.  Maybe it should be reopened.

**Comment by pjotrsavitski** [comment]
Current solution for choosing the targets for the game is manual. The automated logic will follow later. The issue will remain open until more details on the implementation are available.

**Comment by pjotrsavitski** [comment]
We seem to have gone with the solution of manually created Activities (game blueprints).
