### ISSUE TITLE
Render targets

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#25]
Dependent on #21 and #24.
Render targets on the map view.  If there are targets outside the visible area, show arrows pointing towards them at the borders of the view.

**Comment by pjotrsavitski** [comment]
This will probably require doing **map.getBounds()** and then detecting which markers are not present. Then detect the directing from current map centre to the marker and add a visible arrow symbol to the map.

These symbols should be redrawn each time the bounds are changed (if it affects speed, then small check is needed to detect a correct moment and draw the required elements).

**Comment by pjotrsavitski** [comment]
The target set of items/markers is shown on the map. The arrows pointing toward direction of markers not currently shown will not be implemented right now.
