### ISSUE TITLE
Interact with map data

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#27]
Dependent on #21 
Allow the user to rotate, scale, and translate the map view.

**Comment by pjotrsavitski** [comment]
Scale is already available, for mobile devices it will use resize according to corresponding movements of the fingers.

Did not understand the "translate" part. The map could be given language that corresponds with the current language of the system.

The rotate does not seems to be supported for the JS API. Something like that becomes possible with Zoom Level >= 20 while rotateControl being enabled and within the context of SATELLITE or HYBRID maps. Although, it does only work in cases when satellite imagery is available (close-up) and rotation is using increments of 45 degrees.

**Comment by kaimikael** [comment]
Ah, no, "translate" in the sense "subject a body to linear motion with no rotation."  The idea is that a user can drag the map in order to see what's outside the current screen.  Similarly, we want to be able to reorient the map so the user's current walking direction is upwards along the screen.  The map API indeed allows us to present a tilted view of the environment, but that was not what I meant.

**Comment by pjotrsavitski** [comment]
All these abilities except the **reorientation** is there. It is also possible to determine the moving directions, although that is not a feature that Google Maps JS API offers with already available feature set, visuals included. These are the limitations of the current platform. I'll close the issue. Please do create a new standalone that is specifically targeted to some of the missing features.
