### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#3]
There are 3 user roles besides administrator:

1. Zoo administrator
2. Zoo member
3. User (logged in user)

Zoo administrator is zoo-based and is able to edit content belonging to same zoo (zoo members, content created by members and users and assigned to same zoo)

Zoo member role is assigned by zoo administrator upon request. Zoo member is able to create activity pieces and activities within her/his zoo.

User are asked to register or to login for saving current state or sharing results. User is able to create activities based on excisting items and publish them.

**Comment by pjotrsavitski** [comment]
This one should be tackled soon, as roles should be integrated early on and permission checks should be based on those.

**Main administrator** role is missing. These users should have access to everything. Those will be the ones handling the initial role assignments.

How should **zoo-based** be handled? Should the system have a Zoo identifier attached to users and filter things out based on that? A good understanding and definition of that is needed before we can proceed with implementation.
