### ISSUE TITLE
Collecting badges and Mozilla Backpack integration

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#5]
Users may earn badges after completing certain activites which are defined by game creator. Earned badges are displayed on user's profile page and / or via Mozilla Backpack. Badges are sent to MB upon user's request.

**Badges:**
1. Upon successful registration, logging in
2. Connecting user account to social media account
3. Finishing 1 game
4. Finishing 5 games
5. Finishing 10 games
6. Finishing 25 games
7. Adding 1 new activity
8. Adding 5 new activity
9. Adding 10 new activity
10. Adding 25 new activity

**Comment by pjotrsavitski** [comment]
The issue is almost complete and will be closed once a few small issues with Backpack service are resolved.

**Comment by pjotrsavitski** [comment]
We could also use the online badge baking service instead of installing our own: https://github.com/mozilla/openbadges-backpack/wiki/Badge-Baking#using-the-baking-service-rest-api
