### ISSUE TITLE
Image/video content in activity items

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#52]
This is a revival of issue #19: Questions should be able to contain images and/or video/audio.  One of the proposed questions from Tallinn Zoo required the player to watch a YouTube clip to find the answer to the question.  Being able to add images and video/audio, though restricting  to that, should not be too difficult, I hope.

**Comment by pjotrsavitski** [comment]
Video things should be part of the "Embeddable content" question type. There will be a special input that would be happy to take any embed code as an input and how it.

One of Items added by Priit should have that.

**Comment by pjotrsavitski** [comment]
Closing the issue as embeddable question type allows one to add any kind of embed code and then shows it.
