### ISSUE TITLE
Should not be possible to create multiple-choice questions with no correct answer(s) marked

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#53]
Currently it is possible to create activity items with multiple-choice questions, yet leave the correct answer unchosen.  At item creation there should be a check that at least one alternative has been chosen, before accepting to save the item.
(Also, it should not be possible to have empty options.)

**Comment by pjotrsavitski** [comment]
That is a correct point. This should also affect single-choice one. There is not protection, as of the moment.

**Comment by pjotrsavitski** [comment]
The solution will be the same as with **one correct answer** at least one of the choices should be correct. If user manages to uncheck or remove last remaining correct choice. Then system will force-select the first one.
