### ISSUE TITLE
More attractive splash screen for game

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#55]
Currently when starting a game one gets a pane with various statistics about the questions.  This should be replaced with a more attractive splash screen, animated with audio, if possible.
(We need to get a graphics designer on board.  I'll see if I can attract some of our students, but we should gather up a set of this type of issues and attack them all at one go.)

**Comment by pjotrsavitski** [comment]
This could be changed as needed. Playing audio files is also possible (as HTML5 defined the API required and we already require the user to have a modern browser).

Some detailed design is needed for that. Audio files could be kept to a bare minimum (loading too much audiovisual data on non-WiFi could become problematic for some users).

**Comment by pjotrsavitski** [comment]
We have added the screen with the tips for the game. A few other issues point to more concrete ideas. Closing this issue as it has no concrete ideas or implementation details.
