### ISSUE TITLE
Improved feedback during gameplay

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#56]
The current version of the game uses the standard Google pins to indicate activity items.  Their design does not change whether they already have been accessed or not.
When questions are shown and responded to, the player does not get any feedback on whether the response was correct or not.  For some responses, such as video uploads and free text essays this is indeed not possible, and we need to discuss if and how these can be used in game scenarios, as opposed to school class excursion scenarios.  In this latter case, we need to discuss if deferred-feedback and immediate-feedback activities can and should be combined.

I have implemented a demonstration of how feedback can be given in https://188.114.255.12/kai/playview.html, though probably that particular design should not be used.

**Comment by kaimikael** [comment]
OK, there apparently already is a function for indicating feedback, depending on the setting of the type of game.  However, once I had replied to the final question, I was forced to quit the game.  This was confusing.

**Comment by pjotrsavitski** [comment]
Current solution does not display the feedback for the answered question. This is a valid need for automatically-checkable question types. Some visuals could appear and the modal could stay open until user decides to close it (or some countdown could also be implemented; that depends).

As for the feedback. Once the game is over, the modal with results is being displayed (and that is it). Logged in user could access any games that have been played through and see the results screen.

**Comment by pjotrsavitski** [comment]
@kaimikael Do you have any suggestions about how the game should end? Current solution is there to prevent user from interacting with the map as there no longer is anything to do.

If the logic changes to **displaying results for already answered question**, then it could be rethought. Still, if we change the logic, it would need to be completely thought through before making an implementation.

**Comment by kaimikael** [comment]
I think it could make sense to get an overview of what one has responded and feedback on what responses were correct and incorrect, respectively.
Also, as we discussed recently, it would be cool to be able to add "Read more" information to the questions.

**Comment by pjotrsavitski** [comment]
Closing as we have added feedback animations and results modal has been changed. All of that should resolve the issue.
