### ISSUE TITLE
Add localised versions of user interface

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#57]
I presume the toolkit uses resources in order to allow localisation of the user interface.  I can perform the translation into Swedish and Finnish, if I get a hint at what to edit.

**Comment by pjotrsavitski** [comment]
It does, but I did not make the JS side of it translatable yet. This means that playing the game still has hard-coded texts.

Language files for **english** are located here: https://github.com/SmartZoos/Toolset/tree/master/resources/lang/en

Other languages could be added a bit later. Activating the translatable interface could be done one we get everything to be translatable and have the language files.

Please note that once language files are added, these would have to be kept up-to-date. Constantly (this is partially why we still have only english).

**Comment by pjotrsavitski** [comment]
Just as a heads-up: all JS texts have been made translatable (unless something was not notices and will be fixed as soon as spotted). Language switching has also been implemented and should work just fine (except that there are no translations at the moment).

NB! While translating and seeing anything having a colon in front of it (without a space), should not be changed.

Example: **Welcome, :name!**
**:name** should be left as is, that is a placeholder that will be replaced by some value by the system.

**Comment by pjotrsavitski** [comment]
7d6b218f38893abd4ba3cd11de27ca93e66fb591 and 269326f5f38f155df49553ece90ba85273a8427c add Swedish and Finnish translations. The only one missing is Russian.
