### ISSUE TITLE
Items on map should not be selectable until the user gets close enough

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#58]
(I think there might already be a ticket on this somewhere, in which case just close this.)
Currently it is possible to select and respond to activity items anywhere on the map, this should only be possible if the items are close enough to the player.

**Comment by pjotrsavitski** [comment]
This was left like that on purpose. So that people could test things without leaving the room. The code is already there, just disabled. This will be like that until Tallinn Zoo people have finished checking out the current version.

**Comment by tammets** [comment]
Default value: 25m
User may specify radius in meters or leave Activity without radius (suitable for example for "information-trails").
