### ISSUE TITLE
Creating a game - adding markers to map

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#6]
Users are able to set markers on a map which represents certain activites or information locations within a game. Markers are numbered.

**Comment by kaimikael** [comment]
We should clarify that "user" in this case is an "admin", as opposed to a player (who cannot adjust the map).

**Comment by pjotrsavitski** [comment]
Has it been decided that games could only be put together by users with special privileges, not normal users who are just considered to be players and have a more limited capabilities?

**Comment by kaimikael** [comment]
Good point.  We have said that players, once they have levelled up to a requisite level, should be allowed to create questions, but we haven't worked out the details of how that happens yet.  I think we can postpone that issue until we have a working first-level game.

Also: @tammets , is there a particular reason for numbering the markers?

**Comment by pjotrsavitski** [comment]
I can probably answer the numbering part myself. The current prototype shows arrows. This hints to the logical order of how to play the game (this could be important if the game is created by someone not just generated by the system).

**Comment by kaimikael** [comment]
Agreed, numbering should be optional.

**Comment by pjotrsavitski** [comment]
Numbering is currently missing and could be added based on the game type, during some later stages.

Adding items to activity is already possible, although the visuals and logic will have to be made better.
