### ISSUE TITLE
Zoo specific roles need more permissions on related content

### ISSUE THREAD

**Issue by pjotrsavitski** [SmartZoos/Toolset#66]
Users with Zoo specific roles should also be able to have edit and delete rights for the content types that correspond to the case.

**Comment by pjotrsavitski** [comment]
There is one issue with this one. If zoo for some Activity or Item matched with one attached to the role, then user will be able to edit/delete the object. But there is a possibility to change the Zoo during the editing phase. This means that permission might be taken away once the user from Zoo **X** changes that to zoo **Y**.

How should that be addressed, if at all?

Possibilities:
* these roles are not allowed to change the Zoo
* Zoo can not longer be changed after initial creation

@tammets what do you think?

**Comment by tammets** [comment]
Activity Item Owner is able change Zoo X to Zoo Y.
