### ISSUE TITLE
Menu does not open in the default Android brower

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#72]
The menu does not open when using the default Internet app on Android. Pressing the button results in a pressed-down state (the menu icon gets darker). However, the menu does not open and the button remains pressed.

The menu successfully opens in Chrome and Firefox

**Comment by pjotrsavitski** [comment]
Need a version of Android, for the record. But this one probably has something to do with the base library - Bootstrap (switching to a newer version could help).

**Comment by PatriciaMoller** [comment]
Tested on 6.0.1 on Samsung Galaxy J5 and Galaxy S5 Neo

**Comment by pjotrsavitski** [comment]
Just to make sure, does this example work for you: http://getbootstrap.com/examples/starter-template/

or 

you could check out any other from this page: http://getbootstrap.com/getting-started/#examples

Just want to check if that is something generic or specific to SmartZoos codebase. In latter case it could be a lot easier to fix.

**Comment by PatriciaMoller** [comment]
The menus work fine in those links

**Comment by pjotrsavitski** [comment]
Thanks, then it has something to do with the SmartZoos codebase. I will look into that, starting with matching the Bootstrap version used with the latest one (see if it fixes the issue).

**Comment by pjotrsavitski** [comment]
I've spent most of the day trying it out. It ended with running emulators and a lot of testing.

It seems that the integrated browser of Android is unable to handle the file and thus nothing is loaded. The system uses Webpack to multiple modules into one rather big file that has those defined as loadable modules.

I will try to check that further, but as of the moment it seems that the app is not usable with Android stock browser.

One solution would be to move away from Webpack and either use something else or load the files one by one.

The emulator for Android 7.x seemed to only have Chrome and that seemed to be a default browser.

**Comment by pjotrsavitski** [comment]
Please give it a try again. It should be working now. I have not done any extensive testing, but the JS on main page seemed to be ok and game was playable (I've tested on Android 6.0 Nexus 5x API 23 emulator).

Please close the issue if all is well.

This is more of a note to self than explanation: the real server should not be updated with **non-production** builds for generated JS files. This may result in a really huge files that could create this kind of issues. Server will be updated only after production build is enforced and pushed into a repo.

Please close the issue if all is working well.
