### ISSUE TITLE
The feedback button covers the answer option

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#73]
The blue feedback covers the last answers option in the question box. Suggested fix: Move feedback button up or down. Or put to the left-hand side of the screen

See attached image. 
![feedbacktab_screenshot](https://cloud.githubusercontent.com/assets/26867575/24602576/af0def18-185d-11e7-8407-eb158515831f.png)

**Comment by pjotrsavitski** [comment]
It could also be removed from within the game.

**Comment by pjotrsavitski** [comment]
@tammets Does that service have any configuration options for that? If not, then we would have to deal with it somehow.

**Comment by tammets** [comment]
I'll move it to left hand but it can be disabled for mobile phones via service itself.
