### ISSUE TITLE
Activities can not be deleted

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#74]
Pressing the delete button leads to a popup, pressing OK on the prompt leads to an error screen:
![activity cannot be deleted1](https://cloud.githubusercontent.com/assets/26867575/24602847/d2ff3822-185e-11e7-9bc1-5fc235e56f62.PNG)
![activity cannot be deleted2](https://cloud.githubusercontent.com/assets/26867575/24602848/d4266efa-185e-11e7-8539-2ba4f1d01842.PNG)
![activity cannot be deleted](https://cloud.githubusercontent.com/assets/26867575/24602783/a77b4376-185e-11e7-9876-f2fabe511fdb.PNG)

**Comment by pjotrsavitski** [comment]
This would work with activities that have never been played (this has to do with removal of attached files).

I'll fix that one once the course of action has been decided.

**Comment by pjotrsavitski** [comment]
The decision is to enable the so called **soft deletion**. This will not show the item in the UI, while still keeping it within the database. An automated process could later on delete such items with any related data and would also deal with removal of uploaded files (belonging to both Activity itself and any Games).

**Comment by kaimikael** [comment]
I just ran into this problem as well.

**Comment by pjotrsavitski** [comment]
I will get there soon enough (this week).

**Comment by pjotrsavitski** [comment]
Sorry for such a long wait. I will get on it shortly. Will implement a somewhat hybrid approach.

1. If Activity has not been played yet, then it will just be removed forever.
2. If it has been played, then it will just be marked as deleted and will not be shown.

The logic of purging the "softly deleted" ones will be implemented later on as it needs a bit more thinking and was the reason this issue has not been fixed yet.
