### ISSUE TITLE
Activity question change and game completion

### ISSUE THREAD

**Issue by pjotrsavitski** [SmartZoos/Toolset#77]
Game is being marked completed once user gives an answer to the last unanswered question.

This could have a side effect when user can not complete the game if one of the activity items is detached from the Activity. This could only happen when user answers **n-1** question out of total **n** and the last unanswered one is detached.

This would lead to inability to answer a question and trigger the game completion logic.

One possible solution would be to check for game completion each time it is being opened, provided it has not been completed yet. If the system detects a game that could be marked as completed, then it would silently do so.

Another options would be to have some periodic process that checks all incomplete games and marks as needed. This has a few issues, one of those happening transparently and unseen to the user and the other is possibly having to go through a large number of games that do not match such criteria many times in a row.

One more solution would be to detect a possible game being completed without being marked as such and showing user a special button that would trigger the evaluation process and mark the game as being completed.

**Comment by kaimikael** [comment]
What does it mean that a question is detached?

**Comment by pjotrsavitski** [comment]
@kaimikael I did not find any better work for it, but that means that an Activity Item is no longer associated with activity. Yet any games that have been associated with that would still hold the answers given by the people who played during the time it was still part of the Activity.

**Comment by pjotrsavitski** [comment]
Closing as that does not seem to be an issue right now.
