### ISSUE TITLE
Feedback button coveres part of question

### ISSUE THREAD

**Issue by PatriciaMoller** [SmartZoos/Toolset#84]
After the feedback button was moved to the left, the button is covering part of the question. Maybe it could be moved further up/down, or not be visible while answering a question ("hidden" behind the question popup)

![screenshot_20170418-094202](https://cloud.githubusercontent.com/assets/26867575/25120669/5c46d2fe-241f-11e7-8344-f897515300e3.png)

**Comment by pjotrsavitski** [comment]
The feedback functionality is a third party service. We could add some of our own JS code that would be hiding/showing that as needed, yet it could stop working if the service changes.

If this raises issues, then it might be better to remove that from the Gameplay altogether. It could still be included on other pages.

The service also allows disabling that on certain type of devices or screen sizes.

On smaller screen, there would almost always be situations when such element is covering something or gets in the way of some native UI.

**Comment by pjotrsavitski** [comment]
Feedback element has been removed from small devices (phones).
