### ISSUE TITLE
Tooltips within a game

### ISSUE THREAD

**Issue by tammets** [SmartZoos/Toolset#9]
Game creators are able to add tooltips to markers which can be opened any time - even if player is not physically near to certain location. Tooltips are text-based.

**Comment by kaimikael** [comment]
@tammets, what do the tooltips contain?

**Comment by pjotrsavitski** [comment]
These should be InfoWindow objects, using the Google Maps logic. These could contain any text or HTML (including images). Content should not be interactive or have big dimensions.

These are relatively small Information Windows that could be attached to a marker or coordinates.
