### ISSUE TITLE
Change marker positioning to pointing rather than dragging

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#92]
Currently the position marker for an activity item is dragged into place.  As a trail creator I would prefer to point (click) it into place for two reasons:
Navigation is easier if I only have to worry about scrolling and zooming the map, rather than having to drag the marker along as well.
There is a strange discontinuity in the Google Maps representation of Skansen so that when the marker is dragged across this line, the marker jumps away some hundred metres and is lost from immediate view (see attached video).  This is clearly not our bug, but not dragging the marker would work around it.

[Discontinuity.zip](https://github.com/SmartZoos/Toolset/files/976664/Discontinuity.zip)

**Comment by pjotrsavitski** [comment]
It is easily doable. We could even have a hybrid solution that allows both dragging and clicking.

There is a bit of a problem, though. If the marker is being repositioned on click, then each time system detects a click event, and quite many could happen during moving around the map, it could be a bit strange.

The solution might be to use either **double click** or **long click**. In that case we should disable the zooming on **dblclick**.

**Comment by kaimikael** [comment]
Long click makes sense, though will need to be user tested.
