### ISSUE TITLE
Enable/disable position tracking icon needs to be easier to understand

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#93]
When playing an activity, there is a set of icons at the top.  A triangular one turns out to turn position following on and off.  The icon’s function is difficult to understand immediately—especially as the tooltip is not available on a touch display.    
I can't offhand come up with a more immediately understandable icon design, so we should perhaps rather aim at making clear what the icons are.  One suggestion is to briefly animate tooltips for the icons when the player enters the screen.

**Comment by pjotrsavitski** [comment]
We are currently using [materialdesign](https://materialdesignicons.com/) icon font. Any other icon that would make sense from there would be ok. If someone makes any additional set of icons, then those could also easily be included.

Briefly animating the tooltips is doable, yet it could become crowded once all of those are shown. Unless that is done on one-by-one basis with a certain timeout.

It would not be very useful as of the moment, because the system will display a dialog with general Activity information.

One more possibility would be to add a help icon (button). Clicking that would show the animated labels at any time.

**Comment by kaimikael** [comment]
Animated tooltips would clearly have to be done one at a time, and then popped off.  But yes, it might be too busy.  The "i" icon is good, as it is reasonably familiar from other contexts.  Currently it shows statistics on the quiz which I think is mostly useless to a player, so putting up info about how to navigate the interface would be a much better use of the space.

**Comment by pjotrsavitski** [comment]
@kaimikael We've already added explanation for the markers into the information screen. We could extend it further. If the game information is not needed at all, then we could just git rid of it and let that modal dialog become a hub for gameplay data.

Animating the tooltips is possible, but that would require rethinking and changing the way game starts. No dialogs should be opened, but the menu should display the animation with tooltips.

We could also display one [popover](http://getbootstrap.com/javascript/#popovers) (a tooltip with both title and body elements). That one could have the explanation for the whole bar.

**Comment by PatriciaMoller** [comment]
The Google Maps app uses icons like these: ![gps](https://user-images.githubusercontent.com/26867575/33704778-175e04ac-db2e-11e7-96d3-f5dc1b8afee0.PNG) for the "go to my position on the map" button.

May be we can use them too? The[ left one when the tracking is off](https://materialdesignicons.com/icon/crosshairs) and [right when it's on](https://materialdesignicons.com/icon/crosshairs-gps)?

**Comment by pjotrsavitski** [comment]
If we could just replace the current icons with the proposed ones and do not go into the animated tooltips part, then I could make the change and close the issue. If the animated tooltips are still on the table, even after changing the icons, then please create a standalone issue for replacement of the icons and this one would just be left for now, until we get around to the tooltips part.

**Comment by PatriciaMoller** [comment]
No animation needed, just replacing the icons.

**Comment by pjotrsavitski** [comment]
Changed the labels and assigned to December milestone. Will see if I can make it, if not, then it will be done in the beginning of January.
