### ISSUE TITLE
Delay animation when starting game

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#96]
For a player, the current popup window when starting a game does not make much sense: The information shown is the same as was shown in the list of activities and the popup has to be closed in order to actually play the game.  At the same time, the popup only appears after a default animation indicating the loading of the game has been playing for several seconds.  It would be better to have a more entertaining animation playing _while_ the game is loading and for this animation to automatically disappear once the game has finished loading.

**Comment by PatriciaMoller** [comment]
I do agree that the current start popup is not ideal. It should be condensed and remove unneeded info to fit a phone screen. 

To have info show during a loading screen sound fun and a bit more time-effective. Whether having an animation or just bring up the info is better is something to be tested. (And an fitting animation needs to be found/concepted/produced)

The info shouldn't disappear until the player chooses to, in case they didn't have time to read while it loaded.  A "GO!" button gives a much more positive vibe than just closing the window.

**Comment by pjotrsavitski** [comment]
@kaimikael When the user sees the loading screen, the game already has all the information required. The loading screen is there to get the initial players position, at least that is how it is right now. As for the loading animation, well, it was something simple enough that could be replaces by any visuals you could provide.

**Comment by pjotrsavitski** [comment]
@PatriciaMoller A button could be added there easily. Please be more specific about how to limit the information (this should be a concrete suggestion that could be implemented). If you create the suitable animation, it could be integrated. The game data might now be shown at all, if that is not required.

**Comment by pjotrsavitski** [comment]
We have changed the logic, this is no longer relevant. Some of the additional ideas are described in other issues.
