### ISSUE TITLE
Single-item activity gets stuck

### ISSUE THREAD

**Issue by kaimikael** [SmartZoos/Toolset#97]
The “Konstutflykten” activity has a single, multiple-choice, item.
I started the game and opened the question.  The correct answer was already filled-in, possibly (I can’t quite remember) because I had already played the activity once and filled in the correct answer then.
The only option I had was to press the “Exit game” button.

This raises some questions: 
Is it only possible to play a particular activity once?  In that case we should indicate this on the list of activities.  If not, it should be possible to reset (automatically or manually) the previous results in order to play again.
Even if an activity is playable only once, should it be possible to review the questions there?  (For revising purposes or whatever.)  In that case it should be possible to close an opened question and return to the activity map, even if there are no other questions left, in order to feel in control.

**Comment by pjotrsavitski** [comment]
Yes, the same activity could only be completed once by the same user. If it is left unfinished, then it could be completed later (dashboard shown all activities). That was the logic from the initial issues.

Resetting could be made possible, but that requires description of consequences. Example: all the answers are deleted and the system will not hold any information about that. That might not fit well in some contexts. This would also enable **cheating** by answering questions, seeing what is correct and what is not and starting afresh.

Currently, the user will see a list of all results from some activity, once that is complete. If that is not how the logic should be, then it will have to be changed.

**Comment by kaimikael** [comment]
That sounds reasonable, but it does not seem to be what happened to me?

**Comment by pjotrsavitski** [comment]
I could test it out.

There could be some small bug left after refactoring.

If you have that on Toolset, just paste the link here. I will check it right there. If there is a bug, then I will just fix it and update. I'll try to get there in the evening.

**Comment by kaimikael** [comment]
https://toolset.smartzoos.eu/games/bc34faf3-5821-4da4-9cdf-8a65893c7c84/play

**Comment by pjotrsavitski** [comment]
This one happened due to game being finished. It is just not apparent that the game is over and user is shown a results screen.

We need heading text in there that will make it more clear. Any better solutions are also welcome.
